version: '3.8'

services:
  db:
    image: postgres
    restart: always
    # maped port as my mac os alredy uses port 5432
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USERNAME: dealtaskuser
      POSTGRES_PASSWORD: pass@1234
      POSTGRES_DB: DealsTask